# App Reviews Analysis of Philippine Banks

---

This project seeks to analyze the performace of the iOS applications of the top 3 privately owned banks in the Philippines which are Banco De Oro (BDO), Bank of the Philippine Islands (BPI), and Metropolitan Bank & Trust Company (Metrobank) using Natural Language Processing or NLP.

The data is obtained from Apple App Store reviews. This project shows how you can derive insights generated by your users and make decisions based on these insights and data.

## Goal 1: Merge all of the data

---

Before we start doing NLP tasks, we need to combine all of the data from the three banks into one dataframe, so that all of the data transformations would be applied to all of the reviews which is a better approach rahter than doing it one by one per application.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df_bdo = pd.read_csv('datasets/bdo_app_reviews.csv', index_col='Unnamed: 0')
df_bpi = pd.read_csv('datasets/bpi_app_reviews.csv', index_col='Unnamed: 0')
df_metrobank = pd.read_csv('datasets/metrobank_app_reviews.csv', index_col='Unnamed: 0')

### Analyzing the BDO dataset

---

In [3]:
df_bdo.head()

,date,review,rating,isEdited,userName,title
0,8/21/2023 22:42,I tried this one because of the notification i...,1,False,Dence07,Useless app
1,6/29/2023 6:55,I am quite disappointed with the BDO App’s lac...,1,False,Domansss,SMH
2,9/18/2023 14:58,I have this app for a almost a month already a...,1,False,Je123DJ,Not User Friendly
3,8/18/2023 8:18,What are these apps you keep developing? Do th...,1,False,Rieyuxel,Higher a UX Designer!
4,2/3/2022 8:57,Since i have read the reviews and its not appe...,1,False,Abner61,TO MANY BDO APPS but useless.

Looking at the BDO data, it doesn't have a developer response compared to the other two banks. Let's add a new column called `developerResponse`, but let's make it null.

This ensures that we can merge all of the data later with as little friction as possible.

In [4]:
df_bdo['developerResponse'] = np.nan

In [5]:
df_bdo.head()

,date,review,rating,isEdited,userName,title,developerResponse
0,8/21/2023 22:42,I tried this one because of the notification i...,1,False,Dence07,Useless app,NaN
1,6/29/2023 6:55,I am quite disappointed with the BDO App’s lac...,1,False,Domansss,SMH,NaN
2,9/18/2023 14:58,I have this app for a almost a month already a...,1,False,Je123DJ,Not User Friendly,NaN
3,8/18/2023 8:18,What are these apps you keep developing? Do th...,1,False,Rieyuxel,Higher a UX Designer!,NaN
4,2/3/2022 8:57,Since i have read the reviews and its not appe...,1,False,Abner61,TO MANY BDO APPS but useless.,NaN

### Analyzing the Metrobank dataset

---

In [6]:
df_metrobank.head()

,date,developerResponse,review,rating,isEdited,title,userName
0,2023-06-27 04:02:12,"{'id': 37394259, 'body': ""Hi BrownIslandLover,...",I have the old mobile app before which works f...,1,False,The worst mobile banking so far.,BrownIslandLover
1,2022-12-23 04:27:47,"{'id': 33956465, 'body': ""Hi Rick0y, we unders...",For a bank who claims to be “The Best Managed ...,1,False,Disappointing,Rick0y
2,2023-09-15 14:57:38,"{'id': 38978301, 'body': ""Hi LLY40, we're sorr...",I future dated household payroll on the 13th c...,1,False,Unreliable Future Dated Transactions,LLY40
3,2023-08-04 06:02:36,"{'id': 38136728, 'body': 'Hi tine271999, we ap...",i hate this new version of the mobile app. it ...,1,False,unable to transfe to Gcash,tine271999
4,2022-12-22 01:11:56,"{'id': 33951985, 'body': ""Hi BuckPhoti, thank ...","Although buggy, it’s about time the app got mo...",3,False,Good once speed and bugs are fixed,BuckPhoti

Looking at the Metrobank data, there is a developer response but subjectively speaking I really don't like its location there. Becuase data are read from left to right, it gives a position where the feedback is already there while we have yet so see the review and its related data.

Let's move the `developerResponse` column to the last column number so that we can see the review first, the rating, up to the developerResponse; it gives a chronological order to the viewer to see the data in that kind of arrangement.

In [7]:
df_metrobank['developerResponse'] = df_metrobank.pop('developerResponse')

In [8]:
df_metrobank.head()

,date,review,rating,isEdited,title,userName,developerResponse
0,2023-06-27 04:02:12,I have the old mobile app before which works f...,1,False,The worst mobile banking so far.,BrownIslandLover,"{'id': 37394259, 'body': ""Hi BrownIslandLover,..."
1,2022-12-23 04:27:47,For a bank who claims to be “The Best Managed ...,1,False,Disappointing,Rick0y,"{'id': 33956465, 'body': ""Hi Rick0y, we unders..."
2,2023-09-15 14:57:38,I future dated household payroll on the 13th c...,1,False,Unreliable Future Dated Transactions,LLY40,"{'id': 38978301, 'body': ""Hi LLY40, we're sorr..."
3,2023-08-04 06:02:36,i hate this new version of the mobile app. it ...,1,False,unable to transfe to Gcash,tine271999,"{'id': 38136728, 'body': 'Hi tine271999, we ap..."
4,2022-12-22 01:11:56,"Although buggy, it’s about time the app got mo...",3,False,Good once speed and bugs are fixed,BuckPhoti,"{'id': 33951985, 'body': ""Hi BuckPhoti, thank ..."

There, much better.

### Analyzing the BPI dataset

---

In [9]:
df_bpi.head()

,date,review,rating,isEdited,title,userName,developerResponse
0,3/3/2023 14:18,Although this is a strategic departure from th...,2,False,UI is too confusing to the point of giving me ...,LuigiJ10,NaN
1,6/24/2023 10:35,I prefer to do my online banking on my compute...,1,False,Bad. Had to revert to the old app,Chris Cebu,NaN
2,6/21/2023 15:27,I downloaded just to try the app and validate ...,1,False,Senior Citizen UNFRIENDLY,Ornezz,NaN
3,7/2/2023 4:47,So disappointing. I do all my banking transact...,1,False,CANNOT USE THE NEW APP ON MY IPAD,AprilKimLPS,NaN
4,9/16/2023 10:02,Unlike the previous gen app this new one is a ...,1,False,No good,SpunkyChinita,NaN

Nothing can be changed to the BPI dataset, it is good as it is.

### Merging all of the data

---

Now that we have done some initial changes to the data, let's merge all of the data now to be in a one dataframe. To merge it successfully, we need to create an indentifier to each row to know what application did that review come from. You can achieve it by doing the following commands:

In [10]:
df_bdo['bank_app'] = 'Banco De Oro'
df_bpi['bank_app'] = 'Bank of the Philippine Islands'
df_metrobank['bank_app'] = 'Metropolitan Bank & Trust Company'

In [11]:
df_bank_apps_review = pd.concat([df_bdo, df_bpi, df_metrobank], ignore_index=True)

In [12]:
df_bank_apps_review

,date,review,rating,isEdited,userName,title,developerResponse,bank_app
0,8/21/2023 22:42,I tried this one because of the notification i...,1,False,Dence07,Useless app,NaN,Banco De Oro
1,6/29/2023 6:55,I am quite disappointed with the BDO App’s lac...,1,False,Domansss,SMH,NaN,Banco De Oro
2,9/18/2023 14:58,I have this app for a almost a month already a...,1,False,Je123DJ,Not User Friendly,NaN,Banco De Oro
3,8/18/2023 8:18,What are these apps you keep developing? Do th...,1,False,Rieyuxel,Higher a UX Designer!,NaN,Banco De Oro
4,2/3/2022 8:57,Since i have read the reviews and its not appe...,1,False,Abner61,TO MANY BDO APPS but useless.,NaN,Banco De Oro
...,...,...,...,...,...,...,...,...
3770,2022-12-04 11:11:17,locked my account and wont let me log in\nlock...,1,False,a.a.(@),locked my account and wont let me log in,"{'id': 33821654, 'body': ""Hi a.a.(@), we are s...",Metropolitan Bank & Trust Company
3771,2022-12-02 22:39:56,You should be able to use your MetrobankCard.c...,1,False,scaDraM,Very Inconvenient,"{'id': 33821255, 'body': ""Hi scaDraM, thank yo...",Metropolitan Bank & Trust Company
3772,2023-09-21 04:26:47,Did not receive any SMS OTP to open my account...,1,False,Anon8361,SMS OTP,NaN,Metropolitan Bank & Trust Company
3773,2023-09-21 03:52:40,I have been using the app ever since. But why ...,1,False,K̶i̶n̶g̶,App issues logging in,NaN,Metropolitan Bank & Trust Company
3774,2023-09-21 00:05:35,"ang pangit ng new app metrobank online, mas ma...",1,False,dokies56,Request for enhancement,NaN,Metropolitan Bank & Trust Company

### Saving the new data

---

Let's save the data so we can use it later for further analysis.

In [13]:
df_bank_apps_review.to_csv('datasets/all_app_reviews.csv')